version: '3.6'
services:
  fashion-app:
    image: vnanhtuan/fashion-shop:latest     
    restart: always
    ports:
      - 3000:3000
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: vnanhtuan@gmail.com
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: fashionshop.vnanhtuan.com
    volumes:
      - ./nginx/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:





          